"""customos-core — shared contracts for CustomOS."""
from customos_core.identity import (
    canonicalize_url,
    hash_contact,
    normalize_bundle_id,
)
from customos_core.profile import (
    SCHEMA_VERSION,
    AppAffinity,
    BehavioralProfile,
    Browsing,
    Category,
    Contact,
    ContactClass,
    Communication,
    Coverage,
    CoverageRange,
    DomainEntry,
    Durability,
    Idiosyncrasy,
    NegativeSignal,
    NegativeSignalKind,
    Privacy,
    Project,
    ProjectPhase,
    Rhythms,
    Scope,
    Sequence,
    Stability,
    WorkMode,
)

__all__ = [
    # profile schema
    "SCHEMA_VERSION",
    "AppAffinity",
    "BehavioralProfile",
    "Browsing",
    "Category",
    "Contact",
    "ContactClass",
    "Communication",
    "Coverage",
    "CoverageRange",
    "DomainEntry",
    "Durability",
    "Idiosyncrasy",
    "NegativeSignal",
    "NegativeSignalKind",
    "Privacy",
    "Project",
    "ProjectPhase",
    "Rhythms",
    "Scope",
    "Sequence",
    "Stability",
    "WorkMode",
    # identifier normalization
    "canonicalize_url",
    "hash_contact",
    "normalize_bundle_id",
]
